version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener-app
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:dummykeyfordocker
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: urlshortener
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
